name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions ðŸš€
on: [push]
defaults:
  run:
    working-directory: react-map-gl-map-styles
jobs:
  Explore-GitHub-Actions:
    runs-on: windows-latest
    steps:
      - run: npm install
